version: '3'
services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                APP_ENV: ${APP_ENV}
        image: php:8.2-fpm
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            APP_ENV: ${APP_ENV}
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    db:
        image: mongo
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "27047:27017"
        environment:
            TZ: America/Sao_Paulo
            MONGO_INITDB_DATABASE: coodesh-db
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - dbdata:/data/db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
